services:
  chroma-db:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - chroma-data:/data

  backend:
    build:
      context: ./backend
    ports:
      - "8501:8501"
    depends_on:
      - chroma-db
    environment:
      - CHROMA_HOST=chroma-db
      - CHROMA_PORT=8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  chroma-data:
