services:
  chroma-db:
    build:
      context: ./chroma-db
    ports:
      - "5000:5000"
    volumes:
      - chroma-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      retries: 5

  backend:
    build:
      context: ./backend
    ports:
      - "8501:8501"
    depends_on:
      chroma-db:
        condition: service_healthy
    environment:
      - CHROMA_URL=http://chroma-db:5000
    volumes:
      - .:/app

volumes:
  chroma-data:
